### ISSUE TITLE
Documentation summary extraction introduces extra period

### ISSUE THREAD

**Issue by wandernauta** [Ali-chakaroun/ISEP-LivingDocumentation#125]
The following assertion fails:

```
    assertIterableEquals(
        List.of(
            new TypeDescription.Builder(TypeType.CLASS, "Demo")
                .withComment(new CommentSummaryDescription(null, null, "Foo.", null, null))
                .build()),
        parse("/** Foo. */\nclass Demo {}"));
```

because the comment's summary is parsed as `Foo..`, which two periods, rather than `Foo.` with one period. The extra period seems to be introduced by the logic in the `JavadocComment` visitor method on `AnalysisVisitor`.

**Comment by Ali-chakaroun** [comment]
interesting that should have been fixed by concat.
