### ISSUE TITLE
Adjust C# impl to check JSON Schema

### ISSUE THREAD

**Issue by GuusVink** [Ali-chakaroun/ISEP-LivingDocumentation#93]
Including an argumentation for how it is done (copying json schema vs other approach)

**Comment by wandernauta** [comment]
I've done some preliminary research into this.

The JSON parsing library that's used by the C# implementation, [Newtonsoft Json.NET](https://www.newtonsoft.com/json), has built-in JSON Schema support, but that code is marked obsolete and it doesn't seem to support the features our schema uses.

There is an additional library, Newtonsoft Json.NET Schema, that is the designated replacement. However, this library has [a different licensing scheme](https://www.newtonsoft.com/jsonschema#licensing) - I am not a lawyer, but realistically our use of it should probably require one of the business licenses, which is more trouble than it's worth here I think.

So, the minimum approach is perhaps to...

* have the analyzer generate the descriptions,
* serialize them to JSON
* parse that JSON again into some other structure, then
* validate that structure.

This might be slow; on the other hand, perhaps it's not noticeable compared to how long it takes to analyze a project in general. We would have to measure. If it is acceptable, we could for example use [JsonSchema.NET from the json-everything project](https://github.com/gregsdennis/json-everything), which uses [System.Text.Json](https://www.nuget.org/packages/System.Text.Json/) as its JSON parser, as follows: 

```cs
var schema = Json.Schema.JsonSchema.FromFile("path/to/schema.json");
var evaluation = schema.Evaluate(System.Text.Json.Nodes.JsonNode.Parse(result));
if (!evaluation.IsValid)
{
    // Complain
}
```
